# pdf_generator.py
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, inch
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from datetime import datetime
import os

def generate_transformer_pdf(data, output_path="transformer_design.pdf"):
    """
    Generates a professional PDF report from transformer design data.
    """
    # Create directory if not exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # Document setup
    doc = SimpleDocTemplate(output_path, pagesize=A4, topMargin=0.8*inch, bottomMargin=0.6*inch)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        alignment=TA_CENTER,
        spaceAfter=14
    )
    title = Paragraph("Oil-Filled Distribution Transformer Design Report", title_style)
    story.append(title)

    # Subtitle
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=10,
        alignment=TA_CENTER,
        spaceAfter=20
    )
    subtitle = Paragraph(f"Generated on: {datetime.now().strftime('%B %d, %Y at %H:%M')}", subtitle_style)
    story.append(subtitle)

    # Design summary table
    table_data = [
        ["Design Parameter", "Value"],
        ["Rated Power", f"{data['kva']} kVA"],
        ["Primary Voltage (HV)", f"{data['v1']/1000:.1f} kV"],
        ["Secondary Voltage (LV)", f"{data['v2']} V"],
        ["Frequency", f"{data.get('f', 50)} Hz"],
        ["Core Diameter", f"{data['core_diameter_mm']:.1f} mm"],
        ["HV Turns", str(data['hv_turns'])],
        ["LV Turns", str(data['lv_turns'])],
        ["Core Weight", f"{data['core_weight_kg']} kg"],
        ["Copper Weight", f"{data['copper_weight_kg']} kg"],
        ["No-Load Loss", f"{data['no_load_loss_w']} W"],
        ["Load Loss", f"{data['load_loss_w']} W"],
        ["Impedance", f"{data['impedance_percent']}%"],
    ]

    # Create and style table
    table = Table(table_data, colWidths=[220, 150])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('BACKGROUND', (0, 1), (-1, -1), colors.lightgrey),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
    ]))
    story.append(table)
    story.append(Spacer(1, 24))

    # Compliance note
    compliant = data.get('compliant_with_iec', True)
    compliance_msg = "✅ Design complies with standard loss limits." if compliant else "⚠️ Design exceeds standard no-load loss limit."
    compliance_para = Paragraph(compliance_msg, styles['Normal'])
    story.append(compliance_para)
    story.append(Spacer(1, 12))

    # Footer
    footer = Paragraph("Generated by Transformer Design Cloud | For Engineering Use Only", styles['Normal'])
    story.append(footer)

    # Build PDF
    doc.build(story)
    return output_path